### ISSUE TITLE
Vagrant with virtualbox not working

### ISSUE THREAD

**Issue by madhuakula** [apolloclark/vagrant-jenkins-pipeline#1]
This is really cool project. Thanks for this.

When I do the `vagrant up` directly some issue with configurations. To fix this

```
cp aws-config-example.yml aws-config.yml
```

for virtualbox also. This solve the syntax issue and works with virtualbox as well.

**Comment by apolloclark** [comment]
I updated the install instrcutions, added a line to copy the aws-config-example.yml file.

I didn't include aws-config.yml by default, and added it to the .gitignore, since it will be used by anyone doing an Amazon Vagrant deploy, and wanted to prevent them from committing it to their own public or private repos.

Thanks for letting me know! :)

**Comment by madhuakula** [comment]
Cool. Thanks for update
